### ISSUE TITLE
Kd?

### ISSUE THREAD

**Issue by vitorfroes** [Alekitade/game_pesado#1]
Cadê os bregnaite????

**Comment by Alekitade** [comment]
O PROJETO SERÁ STARTADO EM ALGUNS MINUTOS

**Comment by luigioh** [comment]
CALA BOCA

**Comment by luigioh** [comment]
ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO ALE VIADO
